language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
sudo: false
before_script:
- composer self-update
- composer install --prefer-dist --no-interaction
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_3b574c5f323d_key -iv $encrypted_3b574c5f323d_iv
  -in indiewebify-8c3770012eff.json.enc -out indiewebify-8c3770012eff.json -d || true'
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: indiewebify-8c3770012eff.json
  default: true
  project: indiewebify
  on: master
